scope: 'write_fulfillments, write_orders, write_products'

service:
  name: "my-fulfillment-service"
  handle: "my-fulfillment-service"
  callback_url: "http://fulfillment-service.herokuapp.com"
  #callback_url: "https://6fecf05.ngrok.com"
  inventory_management: true
  tracking_support: true
  requires_shipping_method: false
  response_format: "json"

fulfillment_webhook:
  topic: "fulfillments/create"
  address: "http://fulfillment-service.herokuapp.com/fulfill.json"
  #address:  "https://6fecf05.ngrok.com/fulfill.json"
  format: "json"

uninstall_webhook:
  topic: "app/uninstalled"
  address: "http://fulfillment-service.herokuapp.com/uninstall.json"
  #address:  "https://6fecf05.ngrok.com/uninstall.json"
  format: "json"
