service:
  name: "my-fulfillment-service"
  handle: "my-fulfillment-service"
  callback_url: "http://fulfillment-service.herokuapp.com"
  inventory_management: true
  tracking_support: true
  requires_shipping_method: false
  response_format: "json"

fulfillment_webhook:
  topic: "fulfillments/create"
  address: "http://fulfillment-service.herokuapp.com/fulfill.json"
  format: "json"

uninstall_webhook:
  topic: "app/uninstall"
  address: "http://fulfillment-service.herokuapp.com/uninstall.json"
  format: "json"
